// ============================================
// BOOKING DOMAIN - Appointment Entity
// ============================================

import { AppointmentStatus, LocationType } from '@prisma/client';
import type { IEntity } from '@/shared/types/common.types';
import { BusinessRuleViolationError } from '@/shared/errors/base.error';
import { TimeSlot } from '../value-objects/time-slot.vo';

export interface AppointmentProps {
  id: string;
  userId: string;
  employeeId: string;
  serviceId: string;
  date: Date;
  endTime: Date;
  location: LocationType;
  addressId?: string;
  customAddress?: string;
  lat?: number;
  lng?: number;
  status: AppointmentStatus;
  servicePrice: number;
  travelFee: number;
  totalPrice: number;
  notes?: string;
  reminderSent24h: boolean;
  reminderSent2h: boolean;
  cancellationReason?: string;
  cancelledAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class Appointment implements IEntity {
  private constructor(private props: AppointmentProps) {}

  // Factory method
  static create(data: Omit<AppointmentProps, 'id' | 'createdAt' | 'updatedAt'>): Appointment {
    const now = new Date();
    
    const appointment = new Appointment({
      ...data,
      id: '', // Will be generated by DB
      createdAt: now,
      updatedAt: now,
    });

    appointment.validate();
    return appointment;
  }

  // Reconstitute from persistence
  static fromPersistence(data: AppointmentProps): Appointment {
    return new Appointment(data);
  }

  // Getters
  get id(): string {
    return this.props.id;
  }

  get userId(): string {
    return this.props.userId;
  }

  get employeeId(): string {
    return this.props.employeeId;
  }

  get serviceId(): string {
    return this.props.serviceId;
  }

  get date(): Date {
    return this.props.date;
  }

  get endTime(): Date {
    return this.props.endTime;
  }

  get timeSlot(): TimeSlot {
    return TimeSlot.create(this.props.date, this.props.endTime);
  }

  get location(): LocationType {
    return this.props.location;
  }

  get status(): AppointmentStatus {
    return this.props.status;
  }

  get totalPrice(): number {
    return this.props.totalPrice;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  // Business methods
  confirm(): void {
    if (this.props.status !== AppointmentStatus.PENDING) {
      throw new BusinessRuleViolationError(
        'Only pending appointments can be confirmed',
        'CONFIRM_APPOINTMENT'
      );
    }
    this.props.status = AppointmentStatus.CONFIRMED;
    this.props.updatedAt = new Date();
  }

  cancel(reason?: string): void {
    if (
      this.props.status === AppointmentStatus.COMPLETED ||
      this.props.status === AppointmentStatus.CANCELLED
    ) {
      throw new BusinessRuleViolationError(
        'Cannot cancel completed or already cancelled appointment',
        'CANCEL_APPOINTMENT'
      );
    }

    this.props.status = AppointmentStatus.CANCELLED;
    this.props.cancellationReason = reason;
    this.props.cancelledAt = new Date();
    this.props.updatedAt = new Date();
  }

  complete(): void {
    if (this.props.status !== AppointmentStatus.CONFIRMED && 
        this.props.status !== AppointmentStatus.IN_PROGRESS) {
      throw new BusinessRuleViolationError(
        'Only confirmed or in-progress appointments can be completed',
        'COMPLETE_APPOINTMENT'
      );
    }
    this.props.status = AppointmentStatus.COMPLETED;
    this.props.updatedAt = new Date();
  }

  startService(): void {
    if (this.props.status !== AppointmentStatus.CONFIRMED) {
      throw new BusinessRuleViolationError(
        'Only confirmed appointments can be started',
        'START_SERVICE'
      );
    }
    this.props.status = AppointmentStatus.IN_PROGRESS;
    this.props.updatedAt = new Date();
  }

  markReminderSent24h(): void {
    this.props.reminderSent24h = true;
    this.props.updatedAt = new Date();
  }

  markReminderSent2h(): void {
    this.props.reminderSent2h = true;
    this.props.updatedAt = new Date();
  }

  isPast(): boolean {
    return this.props.date < new Date();
  }

  isCancellable(): boolean {
    const now = new Date();
    const hoursDiff = (this.props.date.getTime() - now.getTime()) / (1000 * 60 * 60);
    return (
      hoursDiff >= 2 &&
      (this.props.status === AppointmentStatus.PENDING ||
        this.props.status === AppointmentStatus.CONFIRMED)
    );
  }

  // Validation
  private validate(): void {
    if (!this.props.userId || !this.props.employeeId || !this.props.serviceId) {
      throw new BusinessRuleViolationError('Missing required appointment data');
    }

    if (this.props.date >= this.props.endTime) {
      throw new BusinessRuleViolationError('End time must be after start time');
    }

    if (this.props.totalPrice < 0) {
      throw new BusinessRuleViolationError('Total price cannot be negative');
    }

    if (this.props.location === LocationType.HOME && !this.props.customAddress && !this.props.addressId) {
      throw new BusinessRuleViolationError('Home service requires an address');
    }
  }

  // Convert to plain object
  toObject(): AppointmentProps {
    return { ...this.props };
  }
}
