#!/bin/bash

# ============================================
# Script de génération d'un nouveau domaine DDD
# ============================================

# Couleurs pour les messages
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Vérifier que le nom du domaine est fourni
if [ -z "$1" ]; then
    echo -e "${YELLOW}Usage: ./scripts/create-domain.sh <domain-name>${NC}"
    echo -e "${YELLOW}Example: ./scripts/create-domain.sh user-management${NC}"
    exit 1
fi

DOMAIN_NAME=$1
DOMAIN_PATH="src/domains/${DOMAIN_NAME}"

echo -e "${BLUE}🏗️  Creating domain: ${DOMAIN_NAME}${NC}"

# Créer la structure de répertoires
echo -e "${GREEN}📁 Creating directory structure...${NC}"
mkdir -p "${DOMAIN_PATH}/domain/entities"
mkdir -p "${DOMAIN_PATH}/domain/value-objects"
mkdir -p "${DOMAIN_PATH}/domain/repositories"
mkdir -p "${DOMAIN_PATH}/domain/services"
mkdir -p "${DOMAIN_PATH}/domain/errors"

mkdir -p "${DOMAIN_PATH}/application/use-cases"
mkdir -p "${DOMAIN_PATH}/application/dto"
mkdir -p "${DOMAIN_PATH}/application/services"
mkdir -p "${DOMAIN_PATH}/application/events"

mkdir -p "${DOMAIN_PATH}/infrastructure/persistence/prisma"
mkdir -p "${DOMAIN_PATH}/infrastructure/persistence/mappers"
mkdir -p "${DOMAIN_PATH}/infrastructure/api"
mkdir -p "${DOMAIN_PATH}/infrastructure/messaging"

mkdir -p "${DOMAIN_PATH}/presentation/api/routes"
mkdir -p "${DOMAIN_PATH}/presentation/components"

# Créer le fichier README du domaine
echo -e "${GREEN}📝 Creating README...${NC}"
cat > "${DOMAIN_PATH}/README.md" << EOF
# ${DOMAIN_NAME^} Domain

## Description
[Add domain description here]

## Bounded Context
This domain is responsible for:
- [Responsibility 1]
- [Responsibility 2]
- [Responsibility 3]

## Entities
- [ ] Entity1
- [ ] Entity2

## Value Objects
- [ ] ValueObject1
- [ ] ValueObject2

## Use Cases
- [ ] UseCase1
- [ ] UseCase2

## Events
- [ ] Event1
- [ ] Event2

## Dependencies
- Depends on: [Other domains]
- Used by: [Other domains]

## Status
- [ ] Domain Layer
- [ ] Application Layer
- [ ] Infrastructure Layer
- [ ] Presentation Layer
- [ ] Tests

## Documentation
[Link to detailed documentation]
EOF

# Créer le fichier d'erreurs du domaine
echo -e "${GREEN}🚨 Creating domain errors...${NC}"
cat > "${DOMAIN_PATH}/domain/errors/${DOMAIN_NAME}.errors.ts" << 'EOF'
// ============================================
// DOMAIN - Domain Errors
// ============================================

import { DomainError } from '@/shared/errors/base.error';

export class EntityNotFoundError extends DomainError {
  constructor(id: string) {
    super(\`Entity with ID '\${id}' not found\`, 'ENTITY_NOT_FOUND', 404);
  }
}

// Add more domain-specific errors here
EOF

# Créer le fichier index du domaine
echo -e "${GREEN}📦 Creating index.ts...${NC}"
cat > "${DOMAIN_PATH}/index.ts" << EOF
// ============================================
// ${DOMAIN_NAME^^} DOMAIN - Exports
// ============================================

// Domain Layer
// export * from './domain/entities/...';
// export * from './domain/value-objects/...';
// export * from './domain/repositories/...';
export * from './domain/errors/${DOMAIN_NAME}.errors';

// Application Layer
// export * from './application/use-cases/...';
// export * from './application/dto/...';
// export * from './application/events/...';

// Infrastructure Layer
// export * from './infrastructure/persistence/prisma/...';
// export * from './infrastructure/persistence/mappers/...';
EOF

# Créer un fichier template pour une entité
echo -e "${GREEN}🎯 Creating entity template...${NC}"
cat > "${DOMAIN_PATH}/domain/entities/_entity.template.ts" << 'EOF'
// ============================================
// DOMAIN - Entity Name
// ============================================

import type { IEntity } from '@/shared/types/common.types';
import { BusinessRuleViolationError } from '@/shared/errors/base.error';

export interface EntityProps {
  id: string;
  // Add properties here
  createdAt: Date;
  updatedAt: Date;
}

export class EntityName implements IEntity {
  private constructor(private props: EntityProps) {}

  // Factory method
  static create(data: Omit<EntityProps, 'id' | 'createdAt' | 'updatedAt'>): EntityName {
    const now = new Date();
    
    const entity = new EntityName({
      ...data,
      id: '', // Will be generated by DB
      createdAt: now,
      updatedAt: now,
    });

    entity.validate();
    return entity;
  }

  // Reconstitute from persistence
  static fromPersistence(data: EntityProps): EntityName {
    return new EntityName(data);
  }

  // Getters
  get id(): string {
    return this.props.id;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  // Business methods
  // Add methods here

  // Validation
  private validate(): void {
    // Add validation rules
  }

  // Convert to plain object
  toObject(): EntityProps {
    return { ...this.props };
  }
}
EOF

# Créer un fichier template pour un use case
echo -e "${GREEN}⚡ Creating use case template...${NC}"
cat > "${DOMAIN_PATH}/application/use-cases/_use-case.template.ts" << 'EOF'
// ============================================
// DOMAIN - Use Case Name
// ============================================

import type { IUseCase, Result } from '@/shared/types/common.types';
import { success, failure } from '@/shared/types/common.types';
import type { IEventBus } from '@/shared/events/event-bus';

export interface UseCaseDTO {
  // Add request properties
}

export interface UseCaseResponseDTO {
  // Add response properties
}

interface Dependencies {
  // Add repository and service dependencies
  eventBus: IEventBus;
}

export class UseCaseName implements IUseCase<UseCaseDTO, UseCaseResponseDTO> {
  constructor(private deps: Dependencies) {}

  async execute(dto: UseCaseDTO): Promise<Result<UseCaseResponseDTO>> {
    try {
      // 1. Validation
      
      // 2. Business logic
      
      // 3. Persistence
      
      // 4. Publish events
      
      // 5. Return response
      
      return success({
        // response data
      });
    } catch (error) {
      return failure(error as Error);
    }
  }
}
EOF

echo -e "${GREEN}✅ Domain '${DOMAIN_NAME}' created successfully!${NC}"
echo -e "${BLUE}📂 Location: ${DOMAIN_PATH}${NC}"
echo -e ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "1. Edit ${DOMAIN_PATH}/README.md to describe the domain"
echo -e "2. Create entities in ${DOMAIN_PATH}/domain/entities/"
echo -e "3. Create value objects in ${DOMAIN_PATH}/domain/value-objects/"
echo -e "4. Create repository interfaces in ${DOMAIN_PATH}/domain/repositories/"
echo -e "5. Create use cases in ${DOMAIN_PATH}/application/use-cases/"
echo -e "6. Implement repositories in ${DOMAIN_PATH}/infrastructure/persistence/prisma/"
echo -e ""
echo -e "${BLUE}📚 See docs/MIGRATION_GUIDE.md for more details${NC}"
